### ISSUE TITLE
teardown_request is executed too early

### ISSUE THREAD

**Issue by numblr** [fabianlee/python-flask-streamhtml#1]
In `flask_stream_html.py` you need the code in line 112 (see below) also for the `teardown_request` function to be executed at the right moment, i.e. when the streaming finished. If you don't stream with context the tear down is executed right after the  `after_request` function when the request was started, i.e. before streaming finished.

This is the code from line 111/112:
`# if you needed the request context in generate, then you would use stream_with_context
 #return flask.Response(flask.stream_with_context(generate(static_data)), mimetype='text/html')`

**Comment by fabianlee** [comment]
Thanks, Thomas.  I made the change you pointed out.

**Comment by numblr** [comment]
Cool, and thanks for the nice example btw. ;)
